language: node_js
node_js:
  - lts/*
before_install:
  - pip install --user codecov
  - chmod +x install_node_deps.sh
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - bash install_deps_and_run.sh
env:
  - TRAVIS_BUILD_DIR=./vending_machine
