language: node_js
node_js:
  - lts/*
before_install:
  - pip install --user codecov
install:
  - cd $TRAVIS_BUILD_DIR && npm install
after_success:
  - codecov --file coverage/lcov.info --disable search

env:
  - TRAVIS_BUILD_DIR=./vending_machine
